digitalbazaar/jsonld.js

js/jsonld.js
tests/fromRdf-0001-in.nq
tests/fromRdf-0001-out.jsonld
tests/manifest.jsonld

Fixed dollar characters in comments, added a local test.

Nquads allow comments, fixes

---

README.md

jsonld.js works great with JSPM+systemjs

show JSPM usage

---

js/jsonld.js

No final, but for the sake of discussion.
Fixes #174

Promises compact

---

CHANGELOG.md
tests/test.js

Depends on https://github.com/json-ld/json-ld.org/pull/518

Skip spec version 1.1 tests.

---

.eslintrc
js/jsonld.js

Keeping these style fixes separate.

Style fixes.

---

CHANGELOG.md
lib/compact.js
lib/context.js
lib/expand.js
tests/test-common.js

Adds support for scoped contexts on properties and types for compaction and expansion.

Scoped contexts

---

lib/compact.js
lib/context.js
lib/expand.js
lib/jsonld.js

* Index maps on `@none` or an alias
* Improve container ordering for term selection

Null map update

---

CHANGELOG.md
lib/fromRdf.js

Fixes fromRdf with input triple having a nil subject.
Fixes https://github.com/digitalbazaar/jsonld.js/issues/205.
See test at https://github.com/json-ld/json-ld.org/pull/572.

Check if nil.usages exists.

---

CHANGELOG.md
lib/compact.js
lib/expand.js
lib/frame.js
lib/jsonld.js
lib/nodeMap.js
tests/new-embed-api/frame-0005-in.jsonld
tests/new-embed-api/frame-0005-out.jsonld
tests/new-embed-api/frame-0007-frame.jsonld
tests/new-embed-api/frame-0007-in.jsonld
tests/new-embed-api/frame-0007-out.jsonld
tests/test-common.js

Update to new JSON-LD 1.1 Framing algorithm.

Framing update

---

lib/index.js

This PR addresses this issue - https://github.com/digitalbazaar/jsonld.js/issues/233.

update semversion check to reflect es2018 syntax used

---

CHANGELOG.md
README.md
lib/compact.js
lib/context.js
lib/expand.js
lib/frame.js
lib/graphTypes.js
lib/jsonld.js
lib/nodeMap.js
lib/util.js
tests/new-embed-api/frame-0005-in.jsonld
tests/new-embed-api/frame-0005-out.jsonld
tests/new-embed-api/frame-0007-frame.jsonld
tests/new-embed-api/frame-0007-in.jsonld
tests/new-embed-api/frame-0007-out.jsonld
tests/test-common.js

Tracking PR for 0.6.x work and issues.

0.6.x work-in-progress

---

CHANGELOG.md
lib/jsonld.js
tests/misc.js

From irc convo with @davidlehn.

Add missing await to createNodeMap() and merge().

---

CHANGELOG.md
lib/ActiveContextCache.js
lib/context.js
tests/test-karma.js
webpack.config.js

Use maps and reduce number of lookups to improve find context URL code. Builds on top of #258.

Improve find context urls

---

CHANGELOG.md
lib/fromRdf.js

Fixes https://github.com/digitalbazaar/jsonld.js/issues/294.

Handle "<subject> <rdf:first> <rdf:nil>" triple.

---

CHANGELOG.md
lib/compact.js
lib/context.js
lib/expand.js
lib/util.js
tests/misc.js

Fixes https://github.com/digitalbazaar/jsonld.js/issues/304.

Fix usage of JS Object property names in data.

---

CHANGELOG.md
lib/documentLoaders/xhr.js

Copy & paste issue from Node documentLoader.

Fix XHR document loader Link header processing.

---

CHANGELOG.md
karma.conf.js
webpack.config.js

Fix use of arrows functions in bundles.

---

CHANGELOG.md
karma.conf.js
webpack.config.js

See https://github.com/digitalbazaar/jsonld.js/issues/331#issuecomment-777191220.

Fix use of function* in bundles.

---

package.json
tests/test-karma.js
webpack.config.js

This is a continuation of PR https://github.com/digitalbazaar/jsonld.js/pull/361 (with conflicts resolved).

Switch to core-js@3

---

CHANGELOG.md
README.md
benchmarks/compare/.eslintrc.js
benchmarks/compare/compare.js
benchmarks/compare/package.json
karma.conf.js
tests/earl-report.js
tests/test-common.js
tests/test-karma.js
tests/test.js

- Experimental option used for benchmarking.

Support test loader url rewrite map option.

---

CHANGELOG.md
lib/expand.js
tests/misc.js

- Better handling for `@graph` top-level empty objects, objects with only ids, relative references, etc.

Improve safe mode for `@graph` use cases.

---

CHANGELOG.md
lib/frame.js
tests/test.js

Minor rework of https://github.com/digitalbazaar/jsonld.js/pull/506.

Fix `@json` frame test 0069.

---

CHANGELOG.md
lib/context.js
lib/expand.js
tests/misc.js

- Fix handling of graph property with empty array.
- Fix safe mode for `@graph` use cases.
- Check all elements of graph property with array.

Fix graph property empty array and safe mode.
