digitalbazaar/jsonld.js

- README.md
A small correction to the README.
At least on the browser (not sure if it is the same behaviour in node.js) the documentLoader returns a promise. Passing the callback does nothing.
> Correct documentation of documentLoader usage.

- js/jsonld.js
The spec explicitly allows null values in language maps (section 8.5).
> Ignore null values in language maps

- js/jsonld.js
RDF serialized in N-Quads may contain comments. Comments starting with the `#` character are ignored.
> N-Quads may contain comments. Fixes #121

- js/jsonld.js
Using https://www.w3.org/TR/upgrade-insecure-requests/
Added to the two browser-based document loaders: jquery & xhr
This avoids the Mixed Content errors when requesting non-https URLs which are also available over https. Fixes the security situation without changing the names...more or less.
Hope it's helpful!
🎩
> Fix the Mixed Content mess in XHR Requests

- js/jsonld.js
Reverts digitalbazaar/jsonld.js#165
It has been determined this patch does not work as intended and can cause breakage.
Browsers can still block a request due to mixed content rules which causes this header to never even reach a target server.
When using with a non-secure site the header can cause issues with some sites due to CORS processing rules.  In particular, it currently does not work on www.w3.org.
> Revert "Fix the Mixed Content mess in XHR Requests"

- js/jsonld.js
Hi there,
Pretty self-explanatory, I didn't expect to find the `headers` options to be `node` loader only...
The support of this option is now extended to `jquery` and `xhr` loaders.
I may work on a `fetch` loader in the future, with the approriate polyfill for node, that would mean same code for node and the browser and a promise first API.
> Add headers option support to other loaders

- README.md
The jsonld browser + script tag yielded a different canonical form than when I used the library directly. I confirmed there is a later version that yields the expected results. Updating so others don't run into this as well.
> Update jsonld browser + script tag

- CHANGELOG.md
- lib/expand.js
- lib/fromRdf.js
As called for in json-ld/json-ld.org#558. There is new text in 1.1 (not dependent on `"@version": 1.1`) to ensure that native types won't be coerced to IRIs. It's quite reasonable for 1.0 processors, as such coercion is nonsensical.
> Don't expand non-string native values to node objects.

- CHANGELOG.md
- lib/compact.js
- lib/context.js
- lib/expand.js
- tests/test-common.js
- Set processingMode from options or first encountered context.
- Use array representation of @container in processing.
- Improved error detection for @container variations.
> Improve conformance of processingMode and converge on array representation of @container

- lib/context.js
`@container`, `@id`, `@language`, `@reverse`, and `@type`. This also sets up for additional keywords in 1.1.
> Check for keys in term definition outside that expected

- CHANGELOG.md
- lib/context.js
- lib/url.js
- tests/misc.js
This handles the empty and relative `@base` tests from https://github.com/json-ld/json-ld.org/pull/567.
The absolute and relative iri detection is very weak.  Probably best to have a future pedantic mode that does slow checks on everything and just assume reasonable input for now.  I left a comment pointing to regexes.
Also seems the `parseUrl()` part isn't needed here for abs or rel iris?
> Handle empty and relative @base.

- CHANGELOG.md
- lib/compact.js
- lib/context.js
- lib/expand.js
- lib/graphTypes.js
- lib/jsonld.js
- tests/test-common.js
This adds support for graph indexing on `@id` and `@index`, as well as id maps and type maps.
It is based on the `processingMode` branch, but is targeted for 0.6.x. The 0.6.x branch will require rebasing from 0.5.x until that branch is completed.
> Graph id type maps

- lib/compact.js
- lib/jsonld.js
- tests/test-common.js
which was preventing cases when keyword alias had `@type` defined, as in Compact 0073.
> Remove shortcut from compactIri when iri is a keyword

- CHANGELOG.md
- README.md
- lib/jsonld.js
- tests/misc.js
- tests/test-common.js
Bonus: add `fromRDF()` API tests similar to `toRDF()`.
> Use "application/n-quads" for N-Quads format.

- lib/compact.js
- lib/context.js
- lib/expand.js
- lib/jsonld.js
- tests/test-common.js
Only uses terms with IRIs ending in a delim character, or defined with `@prefix` in 1.1 mode when creating compact IRIs.
> Compact iri changes

- CHANGELOG.md
- lib/compact.js
- lib/context.js
- lib/expand.js
- tests/test-common.js
Note, `_expandObject` is mostly a simple re-factor of the body of `expand`.
Processing of `nests` is done at the end, rather than when encountered, which is required to produce results expected by the test suite.
> Support nested property expansion and compaction.

- tests/test-common.js
- Avoid skipping other potential 1.0 specVersion tests.
- I'm unsure what that test does, but seems it should be skipped explicitly vs skipping all potential 1.0 tests.
- Alternatively to this PR, fix the code so test passes or fix/remove the test.
> Add note about skipping tests.

- CHANGELOG.md
- lib/compact.js
Fixes 1.0 compatibility issue.
> Don't always use arrays for `@graph`.

- CHANGELOG.md
- lib/compact.js
- lib/context.js
- lib/expand.js
- lib/jsonld.js
- lib/util.js
Fixes: https://github.com/digitalbazaar/jsonld.js/issues/262
Optimization using an `asArray()` helper.  This doesn't always use a copy like the concat code, but looks to be ok in these use cases.  Has been sitting around for a while.  There was a small measurable difference in some benchmarks IIRC.
> Add asArray helper.

- CHANGELOG.md
- tests/test-common.js
- Avoid just running a regex on the description and mistakenly skipping
too many tests.  This happened trying to skip an ExpandTest short id
hash that was in both expand-manifest.jsonld and
remote-doc-manifest.jsonld.
- Switch to support idRegex and descriptionRegex.
- Update all skip tests to id regexes that check for manifest name.
> Use explicit id/description test skipping regexes.

- CHANGELOG.md
- karma.conf.js
- tests/test-common.js
- tests/test-karma.js
- tests/test.js
- Improve skip logging.
- Add `skip` and `only` flags in manifests.
- Add `VERBOSE_SKIP=true` env var to debug skipping.
> Improve testing skip features.

- lib/compact.js
- lib/context.js
- lib/expand.js
This PR will cause `@type` scoped terms to be limited to objects that have a matching `@type` value. Without this patch, `@type` scoped terms also unexpectedly apply to anything nested (contained within the tree) of a typed object.
> Fix type scoped terms.

- CHANGELOG.md
- lib/compact.js
- lib/context.js
- lib/expand.js
This PR is for discussion; not to be pulled in yet. This PR would prevent errors from being thrown when overriding protected terms if the override would result in the same definition as before. The only caveat to this is that if the new definition does not include `@protected`, this flag is carried forward to maintain the protection status. Otherwise, the definitions must match precisely, including any scoped contexts.
This tweak makes it much easier to reuse existing contexts that do not have any conflicting definitions in them with new contexts that use `@protected`. Without it, any existing `@context` that defines common things like aliases for `@id` or `@type` would be incompatible with contexts that protect those aliases.
The implementation change involved moving the `@protected` …
> Allow override of a protected term that uses the same definition.

- CHANGELOG.md
- lib/compact.js
- lib/expand.js
- lib/fromRdf.js
- lib/nodeMap.js
- lib/toRdf.js
- lib/util.js
- tests/test-common.js
- tests/webidl/JsonLdProcessor.idl
Closes: https://github.com/digitalbazaar/jsonld.js/issues/296
> Support list of lists.

- CHANGELOG.md
- lib/constants.js
- lib/context.js
- lib/expand.js
- lib/fromRdf.js
- lib/toRdf.js
- package.json
- tests/misc.js
- tests/test-common.js
> Support literal JSON.

- CHANGELOG.md
- tests/test-common.js
(Fixes expand-manifest.jsonld#tp001 and expand-manifest.jsonld#tp002)
> Don't default processingMode to 1.0.

- CHANGELOG.md
- lib/compact.js
- lib/expand.js
- tests/test-common.js
Wrap multiple objects in `@included` when compacting a graph container with multiple object values.
> Don't swallow a graph object when expanding a graph container.

- tests/test-webidl.js
- Travis CI started showing a different letter error. A better fix is
needed but this will just skip the test for now.
This is an odd one.  The interface name changed from t to e on travis?!
I tried updating all the IDL files, but they have changes that didn't immediately work.  So this hack will have to do for now.
> Fix interface name check.

- CHANGELOG.md
- lib/compact.js
- lib/context.js
- lib/expand.js
- lib/util.js
- tests/test-common.js
* Indexing on `@type` requires `@type` to be either `@id` or `@vocab`,  and defaults to `@id`.
* Indexing on an arbitrary property, not just `@index`.
> Updates to indexing

- CHANGELOG.md
- lib/compact.js
- lib/context.js
- tests/test-common.js
`@type` may be used as a term definition only if `"@container": "@set"`.
> Allow compaction of a single type to an array.

- lib/context.js
- lib/documentLoaders/node.js
> @context resolution respects relative URLs.

- CHANGELOG.md
- lib/compact.js
- lib/context.js
- lib/expand.js
- tests/test-common.js
* Use `propagate` and `overrideProtected` options instead of `isTypeScopedContext`/`isPropertyScopedContext`.
* Change createTermDefinition method signature to use hash-based arguments, allowing optional arguments to be passed in.
* Separate processing `@id` and `@type` in expansion, due to differing rules.
* Avoid creating a term definition for `@propagate`. Enables many `@propagate` tests.
Note, this changed context processing fairly substantially.
> Improve Context Propagation

- tests/test-common.js
These skipped test appear to be already fixed. I assume we can just merge this. Of the `@json` tests, just the `null` issue remains.
> Enable tests.

- CHANGELOG.md
- lib/expand.js
So this fixes a bug where the JSON literal version 1 check was being performed on the unexpanded input instead of on the expanded output. IOW, it was looking for `@value` on the unexpanded input and then doing some version 1 check on it if `@type` was not `@json`. If the input uses an alias for `@type` (like `type`) this check will be erroneously triggered and throw an error. Example input:
```
{
"@context": {
"type": "@type"
},
"ex:foo": {
"type": "@json",
"@value": {test: 1}
}
}
```
The conditional should have been checking for `@type` on the expanded output (`expandedParent`) instead -- a similar problem would have occurred if `@value` had been aliased.
However, in fixing this bug we start to fail some test:
`#te029 Verifies that an exception is raised in Expansion when an invalid …
> Fix JSON literal value version 1 check.

- CHANGELOG.md
- lib/context.js
- Add non-keyword fast path check if first char is '@'.
- Avoids full `switch` for data that can't be a keyword.
- Array access will just be undefined for empty string.
- Performance change depends on data shape, format, and processing algorithm workload. Some synthetic tests with ~80% non-keywords could see 1-3%+ overall increase.
I tried various permutations of other `isKeyword` optimizations.  The benchmarking code had too much noise to tell what was best.  But this simple change does appear to have some effect for some (most?) workloads.  I did try a few other things, which should maybe be further explored if needed, but I couldn't tell if they were better or not:
- Change `switch` to `keywordSet.has(v)`.
- Change `switch` to `v in kewordsObject`.
- Change `switch` to …
> isKeyword optimization for non-keyword fast path.

- CHANGELOG.md
- lib/constants.js
- lib/context.js
- lib/documentLoaders/node.js
- lib/documentLoaders/xhr.js
- lib/expand.js
- lib/types.js
- lib/url.js
- tests/test-common.js
A bunch of fixes that address everything other than Framing and some toRdf tests.
- Do minimal checking to see if IRIs are valid by making sure they contain no whitespace.
(804c15b93c9ff7b1c86e965a5feaa5ba0c77b3f0)
- Terms of the form of an IRI must map to the same IRI. (280a01e16bb728f4221055e102408390400f71a1)
- Terms of the form of a relative IRI may not be used as prefixes. (280a01e16bb728f4221055e102408390400f71a1)
- Keep term definitions mapping to null so they may be protected. (2613c4a26cf91d252ae7a713e666d5a90fb78ff1)
- Use localLoader for remote tests. (ff95ee28ecb99e8148c4bcbf949cf4ff7ac767f6)
- Support `rel=alternate`. (080e37445dfc39d16a80d4c56d86ce8ea392c32c)
- Note XHR and Node loaders don't have their own tests.
- Always pass typeScopedContext to _expandObject. …
> Miscellaneous changes

- CHANGELOG.md
- lib/context.js
- tests/test-common.js
It might not be playing nicely with caching, please consider.
> Support for `"@import"`.

- CHANGELOG.md
- lib/compact.js
- lib/context.js
- lib/expand.js
- lib/frame.js
- lib/nodeMap.js
- tests/test-common.js
Code added for framing, but not enabled due to big backlog on framing in general.
> Adds support for `@included` in compaction, expansion and flattening.

- CHANGELOG.md
- lib/context.js
Fixes expand#tec02 & toRdf#tec02.
@gkellogg "keyword redefinition" was not what I expected for this type of error.  Is that more appropriate than the more generic "invalid term definition"?
> Handle term definition on `@type` with empty map.

- CHANGELOG.md
- lib/context.js
Please check.  I'm making tests pass without proper understanding of how this should be working.  Should there be some warning here or is the "ignore" behavior itself important?
> Fix term mapping of `@reverse`.

- CHANGELOG.md
- lib/frame.js
- tests/test-common.js
The code previously would get an invalid frame, if there was a frame object, but it didn't have an `@list` entry.
> Default frame for lists.

- lib/frame.js
This fixes #300 to match behavior in RDF Distiller.
> Expected Behaviour: Given a document with 2 persons "Jane" and "John" and a frame for "givenName": "John" I expect the result to contain only John, but not Jane.
> Actual Behaviour: The result contains both persons, just that Janes givenName is set to null
This moves the initial check on the node to see if it has any properties so that value matches can be checked.
I added a test based on the issue.
(Originally opened #373 but spotted an issue after checking the test-suites -- Now all tests are passing locally.)
> Fix for: Framing does not respect specified value #300

- CHANGELOG.md
- lib/frame.js
- Code was unused and has been removed from the framing spec.
> Remove framing `graphStack` code.

- CHANGELOG.md
- lib/nodeMap.js
- Exclude `@type` from added values in Merge Node Maps step 2.2.1.
- Fix for https://github.com/w3c/json-ld-api/issues/407.
@gkellogg Please check.  This was a quick guess where the code matches the updated algorithm step.
> Fix for Merge Node Maps algorithm.

- CHANGELOG.md
- lib/compact.js
- lib/context.js
- lib/url.js
and don't resolve a relative IRI when setting `@base` in a context, so that the document location can be kept separate from the context itself.
This makes the initial context the same for all processingModes, allowing much more cachability of remote and resolved contexts.
> Don't set `@base` in initial context

- CHANGELOG.md
- lib/ContextResolver.js
- lib/compact.js
- lib/context.js
- lib/url.js
- tests/earl-report.js
- tests/test-common.js
- Add support for context overflow tests: https://github.com/w3c/json-ld-api/pull/416
- Attempt to support older 1.0 error code.  Is this needed?  (It required passing some activeCtx around to get to processing mode)
- Note: The MAX value only detects *depth* of recursion, not total number of remote contexts.  This may be inline with the former "recursion" error code, but seems the "context overflow" should now check total remote contexts loaded (which would also handle depth).  Unsure how to change the code to track that.
> Context overflow.

- CHANGELOG.md
- lib/url.js
- tests/test-common.js
to start path with a '/' for a zero length path if there is an authority in base.
For expand#t0129 and toRdf#te129.
> Fixed `prependBase` 

- CHANGELOG.md
- tests/earl-report.js
- This worked with node and karma.
- Is the 'v' prefix important?
- Our versioning setup uses "3.0.2-0" for dev versions, so when creating real reports would want to checkout a released tag like v3.0.x first. (Or fake it by editing package.json)
> Use package.json version field for EARL reports.

- lib/context.js
Fixes issue #394 
Change was tested against the w3c test suite and seems to fix the issue.
> fix(#394): Clone active context to prevent mutation

- lib/context.js
I've been fighting this error blindly for too long. It's time we shed some light on which terms are causing conflicts when protected.
> fix: states which protected term is being redefined

- .eslintrc.js
- CHANGELOG.md
- lib/jsonld.js
- lib/platform-browser.js
- lib/platform.js
- package.json
- Use `globalThis` to set globals in browser contexts.
- Split platform support out into Node.js and browser files.
Alternate approach to https://github.com/digitalbazaar/jsonld.js/pull/445.
> Use globalThis and split out platform support.

- lib/context.js
- lib/expand.js
- lib/util.js
- tests/misc.js
- tests/test-common.js
As documented in #199 when the value of `@type` or `@id` is a relative IRI it is silently dropped when the resulting expanded object is converted to an RDF representation because RDF does not support relative IRIs. This is problematic for cases where a JSON-LD document is being digitally signed as information can be silently dropped.
This PR expands the `expansionMap` function so that it is called when a relative IRI is encountered when expanding an `@id` or `@type` value. This then allows libraries like [jsonld-signatures](https://github.com/digitalbazaar/jsonld-signatures) to throw errors through a custom [strict expansion map](https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/expansionMap.js#L6-L13).
> Expand expansion map to support calling when a relative IRI is detected

- .eslintrc.js
- .github/workflows/main.yml
- CHANGELOG.md
- lib/documentLoaders/node.js
- lib/documentLoaders/xhr.js
- lib/util.js
- package.json
- tests/test-common.js
- Pulls in newer `ky` and `ky-universal` that should address security
alerts and provide other improvements.
- Newer `ky` will throw errors on redirects even when in `manual`
redirect mode. Now using `throwHttpErrors` option to turn off errors.
- One of the updated dependencies can cause tests to rewrite redirect
`Location` URLs to be relative references. The global `URL` interface
is now used to rebuild a full URL for further redirect processing.
- Newer `node-forge` will output a one-time warning if code even
accesses `response.data`. `@digitalbazar/http-client` will forcefully
set `data` *if* it detects a JSON content type. Calling code can't
know if that happened, so currently needs to redo content detection to
know if JSON `data` can be accessed. This is an issue for sites where …
> Update to `@digitalbazaar/http-client@3`.

- CHANGELOG.md
- lib/events.js
- lib/toRdf.js
- tests/misc.js
These are exposed in errors, but since events are not yet "public", and these are fixes, targeting this as a minor release.
- `relative property reference` event renamed to `relative predicate
reference`.
- `relative type reference` event renamed to `relative object
reference`.
> Fix toRDF event names.

- tests/misc.js
Test showing a potentially non-intuitive issue where `expand` passes safe mode but `toRDF` does not.
> Add expand and toRDF for non-IRI test.

- CHANGELOG.md
- tests/test-common.js
Will enable when rdf-canonize dependency is updated.
> Skip rdf-canon test with U escapes.

- .github/workflows/main.yml
- CHANGELOG.md
- lib/expand.js
- package.json
- Ensure a param is a boolean for clearer debugging.
- Formatting.
> Small cleanups.

- CHANGELOG.md
- benchmarks/compare/compare.js
- lib/events.js
- lib/fromRdf.js
- lib/jsonld.js
- lib/toRdf.js
- tests/misc.js
- tests/test.js
- Emit `toRdf` warning if `@direction` is used and `rdfDirection` is not set.
- Add safe mode support for `@direction`. Using `@direction` without `rdfDirection` set will cause a safe mode failure.
- Add tests.
> Update direction support.

- .gitignore
It should never be committed as it contains upstream test suite content.
> Ignore `test-suites/` directory.
